baseURL: https://thalis.netlify.app/
title: Thalis Rebouças
paginate: '5'
summaryLength: '10'
disableLanguages: []
googleAnalytics: 'G-HQXYFWMZ3J'
disqusShortname: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: Thalis
  description: Feito por Thalis Rebouças
  favicon: images/lcon.png
  logo_dark: images/logo-dark.png
  logo_light: images/logo.png
  logo_width: 150px
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
      - link: plugins/hover/hover.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/owl-carousel/owl.carousel.min.css
      - link: plugins/owl-carousel/owl.theme.default.min.css
      - link: plugins/text-animation/text-animation.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/wow.min.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/jquery.waypoints.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/owl-carousel/owl.carousel.min.js
  preloader:
    enable: yes
    preloader: images/loading.gif
  social:
    - icon: ti-twitter-alt
      link: https://twitter.com/ThalisReboucas
    - icon: ti-facebook
      link: https://www.facebook.com/thalisreboucas
    - icon: ti-instagram
      link: https://www.instagram.com/thalisreboucas
    - icon: ti-github
      link: https://github.com/thalisreboucas
    - icon: ti-linkedin
      link: https://www.linkedin.com/in/thalisreboucas
Languages:
  en:
    contentDir: content/english
    copyright:  <small>Copyright &copy; Thalis 2021 .Todos os direitos reservados.</small> <br>  <Small> Tema do <a href="https://somrat.netlify.com">somrat</a>. Site feito em Hugo com <a href="https://bookdown.org/yihui/blogdown/">Blogdown</a>.</Small>    
    home: Home
    languageCode: pt-br
    languageName: PT
    menu:
       main:
        - name: Home
          url: /
          weight: 1
        - name: Sobre Mim
          pre: '#'
          url: about
          weight: 2
        - name: Habilidades
          pre: '#'
          url: service
          weight: 3
        - name: Blog
          url: blog
          weight: 4
        - name: Contato
          pre: '#'
          url: contact
          weight: 5
        
    weight: 1
  
